language: ruby
rvm:
  - 2.4.1

notifications:
  email: false

services:
  - postgresql

cache: bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_install:
  - sudo apt-get install sphinxsearch

after_success:
- bundle exec codeclimate-test-reporter

script:
  - 'bundle exec rake spec'

gemfile:
  - Gemfile
