dist: trusty
sudo: required

addons:
  apt:
    sources:
      - google-chrome

    packages:
      - google-chrome-stable

  code_climate:
    repo_token: 4e3cb2a696643d430b41c961c4f77f46e01499ad

before_script:
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/database.travis.yml config/database.yml

services:
  - postgresql

after_success:
  - bundle exec codeclimate-test-reporter
