language: ruby
dist: trusty
sudo: required

rvm:
  - 1.29.1

env:
  - DB=postgresql
cache: bundler

addons:
  apt:
    sources:
      - google-chrome

    packages:
      - google-chrome-stable

  code_climate:
    repo_token: 4e3cb2a696643d430b41c961c4f77f46e01499ad

before_script:
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/database.travis.yml config/database.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

services:
  - postgresql

after_success:
  - bundle exec codeclimate-test-reporter
