dist: trusty
sudo: required
language: ruby

rvm:
  - 1.29.1

addons:
  apt:
    sources:
      - google-chrome

    packages:
      - google-chrome-stable

  code_climate:
    repo_token: 4e3cb2a696643d430b41c961c4f77f46e01499ad

before_script:
  - psql -c 'create database prog_test' -U postgres
  - cp config/database.yml.travis config/database.yml

services:
  - postgresql

after_success:
  - bundle exec codeclimate-test-reporter
