version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/images/app/development/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www/thinknetica
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    links:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=123654
      - POSTGRES_USER=sitennov
      - POSTGRES_DB=sitennov_development
    volumes:
      - ~/volume/postgres-data:/var/lib/postgresql/data