version: '2'

services:
  db:
    image: postgres:9.6
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=123654
      - POSTGRES_USER=sitennov
      - POSTGRES_DB=sitennov_development
    volumes_from:
      - shared_store
      
  shared_store:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
